#!/usr/bin/env sh

SPECFILE="opentracker.spec"

set -e

#  Get the full path to the spec file
SPECFILE=$(dirname "$(realpath "$0")")/$SPECFILE

#  Parse the package name, version and release out of the spec file
NAME=$(sed -n 's/^Name:[[:space:]]*//p' "$SPECFILE")
VERSION=$(sed -n 's/^Version:[[:space:]]*//p' "$SPECFILE")
RELEASE=$(sed -n 's/^Release:[[:space:]]*//;s/%{?dist}//p' "$SPECFILE")
SOURCE0=$(sed -n 's/^Source0:[[:space:]]*//p' "$SPECFILE")
SOURCE0=$(echo $SOURCE0 | sed "s/%{name}/${NAME}/g;s/%{version}/${VERSION}/g")

if [ $(cat /etc/hostname) == "fang.localdomain" ]; then

	echo "Fetching source code and building Source0 tar.gz file ..."
	MY_PATH=$(dirname "$(realpath "$0")")
	rm -fr /tmp/${NAME}-$VERSION
	mkdir /tmp/${NAME}-$VERSION
	cd /tmp/${NAME}-$VERSION
	cvs -d :pserver:cvs@cvs.fefe.de:/cvs -z9 co libowfat
	git clone git://erdgeist.org/opentracker
	cd /tmp
	tar -czf /home/dlk/rpmbuild/SOURCES/${SOURCE0} ${NAME}-$VERSION
	rm -fr libowfat opentracker
	cd "$MY_PATH"

	echo "Building $NAME in centos-rpmbuild:8 container ..."
	podman run --interactive --name=rpmbuild --rm --tty --volume=${HOME}:${HOME} localhost/centos-rpmbuild:8 "$(realpath "$0")"
	#podman run --interactive --name=rpmbuild --rm --tty --volume=${HOME}:${HOME} localhost/centos-rpmbuild:8 /bin/sh
	
else

	#echo -e "\nUpdate system software ..."
	dnf upgrade -y
	dnf install -y zlib-devel

	echo -e "\nGet the Source0 file ..."
	mkdir -p /root/rpmbuild/SOURCES
	cp /home/dlk/rpmbuild/SOURCES/$SOURCE0 /root/rpmbuild/SOURCES/
	
	#  Build the packages ...
	rpmbuild -ba "$SPECFILE"

	echo -e "\nCopying RPM files to host system ..."
	mv ${HOME}/rpmbuild/RPMS/x86_64/${NAME}-${VERSION}-${RELEASE}.*.x86_64.rpm /home/dlk/rpmbuild/RPMS/x86_64/
	mv ${HOME}/rpmbuild/SRPMS/${NAME}-${VERSION}-${RELEASE}.*.src.rpm /home/dlk/rpmbuild/SRPMS/
	
fi
