#!/usr/bin/env bash

set -e

if [ $(cat /etc/hostname) == "fang.localdomain" ]; then

	echo -e "\nBuilding transmission in centos-rpmbuild:8 container ..."
	podman run --interactive --name=rpmbuild --rm --tty --volume=${HOME}:${HOME} localhost/centos-rpmbuild:8 /bin/sh -c "$(realpath "$0")"

else

	echo -e "\nUpdate system software ..."
	dnf -y upgrade
	dnf -y install openssl-devel glib2-devel gtk3-devel libnotify-devel libcanberra-devel libcurl-devel dbus-glib-devel libevent-devel desktop-file-utils gettext intltool qt5-qtbase-devel systemd-devel libappindicator-gtk3-devel

	echo -e "\nInstall the source RPMS ..."
	rpm -Uvh /home/dlk/src/centos-rpms/transmission/*.el7.src.rpm
	
	echo -e "\nBuilding libnatpmp ..."
	rpmbuild -ba /root/rpmbuild/SPECS/libnatpmp.spec
	
	echo -e "\nInstalling libnatpmp-devel ..."
	dnf install -y /root/rpmbuild/RPMS/x86_64/libnatpmp-20150609-1.el8.x86_64.rpm /root/rpmbuild/RPMS/x86_64/libnatpmp-devel-20150609-1.el8.x86_64.rpm
	
	echo -e "\nBuilding transmission ..."
	rpmbuild -ba /root/rpmbuild/SPECS/transmission.spec

	echo -e "\nCopying RPM files to host system ..."
	mv ${HOME}/rpmbuild/RPMS/x86_64/*.el8.x86_64.rpm /home/dlk/rpmbuild/RPMS/x86_64/
	mv ${HOME}/rpmbuild/SRPMS/*.el8.src.rpm /home/dlk/rpmbuild/SRPMS/

fi
